# Site settings
title: "What an Egg"
logo: whatanegg_logo-18.png
email: poached@whatanegg.com
description: ""
url: "http://whatanegg.com" # the base hostname & protocol for your site
baseurl: "" # the subpath of your site, e.g. /blog/
twitter_username: whatanegg_0

permalink: pretty
paginate: 5

# Build settings
markdown: kramdown
highlighter: rouge

gems:
  - jekyll-sitemap
  - jekyll-paginate
